services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: db01blog
      MYSQL_USER: abdo
      MYSQL_PASSWORD: userpass123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # This command fixes authentication issues with MySQL 8.0
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

volumes:
  mysql_data: